#spring:
#  application:
#    name: yifang-app
#  profiles:
#    active: dev

server:
  port: 10914
  # ==============================================================
  servlet:
    context-path: /yuuki/test/
spring:
    profiles:
      active: dev
    jackson:
      serialization:
        write-dates-as-timestamps: true

mapper:
  mappers: com.malaxiaoyugan.test.BaseMapper
  not-empty: false
  identity: mysql
# mybatis
mybatis:
  type-aliases-package: com.mxd.dao.entity
  mapper-locations:  classpath*:mapper/*.xml
  configuration:
    jdbc-type-for-null: 'null'
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# ==============================================================

#微信后台回调
wexinpay:
  notify:
    url: https://***/weixin/pay




mongodb:
  #用户登录db
  authenticationDatabase: common_job
  #操作数据库db
  db: common_job
  username: wenge
  password: 123456
  hosts:
    - 127.0.0.1
    #- 127.0.0.1
    #- 127.0.0.1
  ports: 27017
  #客户端的连接数
  connections-per-host: 20
  #客户端最小连接数
  min-connections-per-host: 0
  replica-set: