spring:
    datasource:
        yuuki-forum:
            url: jdbc:mysql://106.13.15.122:3306/forum?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
            username: root
            password: 123456
            type: com.alibaba.druid.pool.DruidDataSource
            driver-class-name: com.mysql.cj.jdbc.Driver
            initialSize: 5
            minIdle: 5
            maxActive: 20
            maxWait: 60000
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
            validationQuery: SELECT 1 FROM DUAL
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            poolPreparedStatements: true
            connection-properties: druid.stat.mergeSql:true;druid.stat.slowSqlMillis:5000
        yuuki-admin:
            url: jdbc:mysql://106.13.15.122:3306/admin?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
            username: root
            password: 123456
            type: com.alibaba.druid.pool.DruidDataSource
            driver-class-name: com.mysql.cj.jdbc.Driver
            initialSize: 5
            minIdle: 5
            maxActive: 20
            maxWait: 60000
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
            validationQuery: SELECT 1 FROM DUAL
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            poolPreparedStatements: true
            connection-properties: druid.stat.mergeSql:true;druid.stat.slowSqlMillis:5000
            # ==============================================================
    redis:
        host: 106.13.15.122
        port: 6379
        password: test123456
        timeout: 5000
        database: 3
        pool:
            testOnBorrow: true
            numTestsPerEvictionRun: 1024
            timeBetweenEvictionRunsMillis: 30000
            minEvictableIdleTimeMillis: 1800000
            softMinEvictableIdleTimeMillis: 1800000
            testWhileIdle: true
            blockWhenExhausted: false
        jedis:
            pool:
                max-idle: 1000
                min-idle: 1
                max-wait:
    thymeleaf:
        cache: false

fdfs:
    so-timeout: 1501
    connect-timeout: 601
    thumb-image:             #缩略图生成参数
        width: 200
        height: 200
    tracker-list:
        - 43.254.45.11:22122


es:
    host: 106.53.237.234
    port: 9200
    token: es-token
    charset: UTF-8
    scheme: http
    client:
        connectTimeOut: 5000
        socketTimeout: 15000

rabbitmq:
    host: 128.1.49.194
    port: 5672
    username: yuuki
    password: 33310914
    virtual-host: /
    publisher-confirms: true
    publisher-returns: true
    # 开启ACK
    listener:
        simple:
            acknowledge-mode: manual